### ISSUE TITLE
typed-ast doesn't build on python 3.11

### ISSUE THREAD

**Issue by zsol** [ezyang/ghstack#112]
`poetry install` fails on CPython 3.11.0b5 (and later), because typed-ast doesn't build with this version of CPython:
```
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/zsol/.cache/pypoetry/virtualenvs/ghstack-vElzcM4T-py3.11/include -I/home/zsol/.asdf/installs/python/3.11.0b5/include/python3.11 -c yarl/_quoting_c.c -o build/temp.linux-x86_64-cpython-311/yarl/_quoting_c.o
        yarl/_quoting_c.c:196:12: fatal error: longintrepr.h: No such file or directory
          196 |   #include "longintrepr.h"
              |            ^~~~~~~~~~~~~~~
```

`longintrepr.h` has been moved into `cpython/longintrepr.h`. In any case `typed-ast` is going away, and most of its functionality is provided by the builtin `ast` module since 3.8.

Maybe something like this would work? https://github.com/psf/black/blob/44d5da00b520a05cd56e58b3998660f64ea59ebd/src/black/parsing.py#L27-L40

**Comment by ezyang** [comment]
Can't we just dump `mypy_extensions`?

**Comment by zsol** [comment]
Huh, but mypy has this correctly: https://github.com/python/mypy/blob/master/setup.py#L211 Are we pinning on an old version?

**Comment by ezyang** [comment]
yeah, poetry lockfile. Try upgrading it.

**Comment by amyreese** [comment]
#137 fixes this
